export enum ERROR_CODE {
  // AUTHENTICATION
  AUTHENTICATION_USER_NOT_FOUND = 'AUTHENTICATION_USER_NOT_FOUND',
  AUTHEN_USER_WRONG_USER_OR_PASS = 'AUTHEN_USER_WRONG_USER_OR_PASS',
  PAGE_SIZE_BIGGER_THAN_0 = 'PAGE_SIZE_BIGGER_THAN_0',
  PAGE_INDEX_MUST_BE_POSITIVE = 'PAGE_INDEX_MUST_BE_POSITIVE',
  // ROLE
  ROLE_NAME_ALREADY_EXIST = 'ROLE_NAME_ALREADY_EXIST',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  // API
  API_PATH_ALREADY_EXIST = 'API_PATH_ALREADY_EXIST',
  API_NOT_FOUND = 'API_NOT_FOUND',
  // PERMISSION
  PERMISSION_NAME_ALREADY_EXIST = 'PERMISSION_NAME_ALREADY_EXIST',
  // ACCOUNT
  ACCOUNT_PHONE_OR_EMAIL_ALREADY_EXIST = 'ACCOUNT_PHONE_OR_EMAIL_ALREADY_EXIST',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_NOT_ACTIVE = 'ACCOUNT_NOT_ACTIVE',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  ACCOUNT_PASSWORD_NOT_MATCH = 'ACCOUNT_PASSWORD_NOT_MATCH',
  // ACCOUNT_ROLE
  ACCOUNT_ROLE_ALREADY_HAS_ROLE = 'ACCOUNT_ROLE_ALREADY_HAS_ROLE',
  // ROLE_PERMISSION_PAIR
  ROLE_PERMISSION_PAIR_ALREADY_EXIST = 'ROLE_PERMISSION_PAIR_ALREADY_EXIST',
  ACCOUNT_IDENTITY_ALREADY_EXIST = 'ACCOUNT_IDENTITY_ALREADY_EXIST',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ROLE_WAS_USED = 'ROLE_WAS_USED',

  //file
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  NO_CHANGE_TO_GIVE_POINT = 'NO_CHANGE_TO_GIVE_POINT',

  LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND",

  RATED = "RATED"
}
