export enum RESPONSE_CODE {
  // AUTHENTICATION
  SUCCESS = "SUCCESS",
  CREATE_USER_SUCCESS = 'CREATE_ADMIN_SUCCESS',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  AUTHENTICATION_USER_NOT_FOUND = 'AUTHENTICATION_USER_NOT_FOUND',
  AUTHEN_USER_WRONG_USER_OR_PASS = 'INVALID_USER_NAME_OR_PASSWORD',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
  // ROLE
  ROLE_NAME_ALREADY_EXIST = 'ROLE_NAME_ALREADY_EXIST',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  // API
  API_PATH_ALREADY_EXIST = 'API_PATH_ALREADY_EXIST',
  API_NOT_FOUND = 'API_NOT_FOUND',
  // PERMISSION
  PERMISSION_NAME_ALREADY_EXIST = 'PERMISSION_NAME_ALREADY_EXIST',
  // ACCOUNT
  ACCOUNT_PHONE_OR_EMAIL_ALREADY_EXIST = 'ACCOUNT_PHONE_OR_EMAIL_ALREADY_EXIST',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_PASSWORD_NOT_MATCH = 'ACCOUNT_PASSWORD_NOT_MATCH',
  // ACCOUNT_ROLE
  ACCOUNT_ROLE_ALREADY_HAS_ROLE = 'ACCOUNT_ROLE_ALREADY_HAS_ROLE',
  // ROLE_PERMISSION_PAIR
  ROLE_PERMISSION_PAIR_ALREADY_EXIST = 'ROLE_PERMISSION_PAIR_ALREADY_EXIST',
}
